// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.ExternalLoginModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.ForgotPasswordModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.EmailModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.IndexModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.RegisterModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.ResendEmailConfirmationModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.ResetPasswordModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWith2faModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.ChangePasswordModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "type", Target = "~T:Donovan.Game.Web.Areas.Identity.Pages.Account.Manage.SetPasswordModel.InputModel")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.ExternalLoginModel.OnPost(System.String,System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.ExternalLoginModel.OnGetCallbackAsync(System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.ExternalLoginModel.OnPostConfirmationAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginModel.OnPostAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWith2faModel.OnPostAsync(System.Boolean,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.OnGetAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.OnPostAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.LogoutModel.OnPost(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.RegisterModel.OnGetAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "This code is part of the ASP.NET Core Identity scaffolding.", Scope = "member", Target = "~M:Donovan.Game.Web.Areas.Identity.Pages.Account.RegisterModel.OnPostAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is recommended for applications (see ConfigureAwait FAQ).", Scope = "module")]
