# Development Pipeline
name: $(versionMajor).$(versionMinor).$(versionPatch)-$(versionPrelease)+$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - '*'
    exclude:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionMajor: '0'
  versionMinor: '1'
  versionPatch: '0'
  versionPrelease: 'dev'
  versionBuildMetadata: ''

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Run Azure Storage Emulator'
  inputs:
    script: |
      "%ProgramFiles(x86)%\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe" init /server "(localdb)\MSSQLLocalDB"
      "%ProgramFiles(x86)%\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe" start

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(BuildConfiguration)\**\*.Tests.dll
